# Generated by webbed_duck.core.compiler
ROUTE = {'allowed_formats': [],
 'assets': None,
 'cache_mode': 'materialize',
 'charts': [{'id': 'greeting_length', 'type': 'line', 'y': 'greeting_length'}],
 'constant_params': {},
 'constants': {},
 'default_format': None,
 'description': 'Return a greeting using DuckDB',
 'directives': [],
 'id': 'hello_world',
 'interpolation': {'segments': ["SELECT\n  'Hello, ' || ",
                                " || '!' AS greeting,\n"
                                "  'Personalized greeting rendered by DuckDB' AS "
                                'note,\n'
                                "  LENGTH('Hello, ' || ",
                                " || '!')::INT AS greeting_length,\n"
                                '  CURRENT_TIMESTAMP AS created_at;'],
                   'slots': [{'column': 16,
                              'expr': 'name',
                              'filters': [],
                              'line': 2,
                              'name': 'name',
                              'requires_path_guard': False},
                             {'column': 23,
                              'expr': 'name',
                              'filters': [],
                              'line': 4,
                              'name': 'name',
                              'requires_path_guard': False}],
                   'template_sql': 'SELECT\n'
                                   "  'Hello, ' || __wd_slot_0__ || '!' AS greeting,\n"
                                   "  'Personalized greeting rendered by DuckDB' AS "
                                   'note,\n'
                                   "  LENGTH('Hello, ' || __wd_slot_1__ || '!')::INT "
                                   'AS greeting_length,\n'
                                   '  CURRENT_TIMESTAMP AS created_at;'},
 'metadata': {'append': {'columns': ['greeting', 'note', 'created_at'],
                         'destination': 'hello_appends.csv'},
              'cache': {'invariant_filters': [{'column': 'greeting_length',
                                               'param': 'greeting_length',
                                               'type': 'int',
                                               'ui_label': 'Greeting length'}],
                        'order_by': ['created_at'],
                        'ttl_hours': 12},
              'charts': [{'id': 'greeting_length',
                          'type': 'line',
                          'y': 'greeting_length'}],
              'feed': {'summary_col': 'note',
                       'timestamp_col': 'created_at',
                       'title_col': 'greeting'},
              'html_c': {'meta_cols': ['note', 'created_at'],
                         'show_params': ['name', 'greeting_length'],
                         'title_col': 'greeting'},
              'html_t': {'show_params': ['name', 'greeting_length']},
              'overrides': {'allowed': ['note'], 'key_columns': ['greeting']}},
 'methods': ['GET'],
 'param_order': [],
 'params': [{'default': 'world',
             'description': 'Name to greet',
             'extra': {'ui_control': 'input',
                       'ui_help': 'Type a name and press Apply to refresh the greeting',
                       'ui_label': 'Name',
                       'ui_placeholder': 'Your teammate'},
             'name': 'name',
             'required': False,
             'template_only': True,
             'type': 'str'}],
 'path': '/hello',
 'postprocess': {'feed': {'summary_col': 'note',
                          'timestamp_col': 'created_at',
                          'title_col': 'greeting'},
                 'html_c': {'meta_cols': ['note', 'created_at'],
                            'show_params': ['name', 'greeting_length'],
                            'title_col': 'greeting'},
                 'html_t': {'show_params': ['name', 'greeting_length']}},
 'prepared_sql': 'SELECT\n'
                 "  'Hello, ' || __wd_slot_0__ || '!' AS greeting,\n"
                 "  'Personalized greeting rendered by DuckDB' AS note,\n"
                 "  LENGTH('Hello, ' || __wd_slot_1__ || '!')::INT AS "
                 'greeting_length,\n'
                 '  CURRENT_TIMESTAMP AS created_at;',
 'preprocess': [],
 'raw_sql': 'SELECT\n'
            "  'Hello, ' || {{name}} || '!' AS greeting,\n"
            "  'Personalized greeting rendered by DuckDB' AS note,\n"
            "  LENGTH('Hello, ' || {{name}} || '!')::INT AS greeting_length,\n"
            '  CURRENT_TIMESTAMP AS created_at;',
 'returns': 'relation',
 'title': 'Hello world',
 'uses': [],
 'version': None}
