# Generated by webbed_duck.core.compiler
ROUTE = {'description': 'Return a greeting using DuckDB',
 'id': 'hello_world',
 'metadata': {'append': {'columns': ['greeting', 'note', 'created_at'],
                         'destination': 'hello_appends.csv'},
              'charts': [{'id': 'greeting_length',
                          'type': 'line',
                          'y': 'greeting_length'}],
              'feed': {'summary_col': 'note',
                       'timestamp_col': 'created_at',
                       'title_col': 'greeting'},
              'html_c': {'meta_cols': ['note', 'created_at'], 'title_col': 'greeting'},
              'overrides': {'allowed': ['note'], 'key_columns': ['greeting']}},
 'methods': ['GET'],
 'param_order': ['name', 'name'],
 'params': [{'default': 'world',
             'description': 'Name to greet',
             'name': 'name',
             'required': False,
             'type': 'str'}],
 'path': '/hello',
 'prepared_sql': 'SELECT\n'
                 "  'Hello, ' || ? || '!' AS greeting,\n"
                 "  'Personalized greeting rendered by DuckDB' AS note,\n"
                 "  LENGTH('Hello, ' || ? || '!')::INT AS greeting_length,\n"
                 '  CURRENT_TIMESTAMP AS created_at;',
 'raw_sql': 'SELECT\n'
            "  'Hello, ' || {{name}} || '!' AS greeting,\n"
            "  'Personalized greeting rendered by DuckDB' AS note,\n"
            "  LENGTH('Hello, ' || {{name}} || '!')::INT AS greeting_length,\n"
            '  CURRENT_TIMESTAMP AS created_at;',
 'title': 'Hello world'}
