# Generated by webbed_duck.core.compiler
ROUTE = {'description': 'Return a greeting using DuckDB',
 'id': 'hello_world',
 'methods': ['GET'],
 'param_order': ['name'],
 'params': [{'default': 'world',
             'description': 'Name to greet',
             'name': 'name',
             'required': False,
             'type': 'str'}],
 'path': '/hello',
 'prepared_sql': "SELECT 'Hello, ' || ? || '!' AS greeting;",
 'raw_sql': "SELECT 'Hello, ' || {{name}} || '!' AS greeting;",
 'title': 'Hello world'}
