name: Publish to PyPI (OIDC)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  id-token: write   # Required for PyPI Trusted Publisher (OIDC)
  contents: read

concurrency:
  group: pypi-publish
  cancel-in-progress: false

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    environment:
      name: pypi   # Must match the Environment name you configured on PyPI

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip and install build backend
        run: |
          python -m pip install --upgrade --trusted-host pypi.org --trusted-host files.pythonhosted.org pip
          python -m pip install --upgrade --trusted-host pypi.org --trusted-host files.pythonhosted.org build

      - name: Build sdist and wheel
        run: python -m build --sdist --wheel --outdir dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

      # Publish to PyPI using OpenID Connect (no API token needed)
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true
          verbose: true
          print-hash: true
          attestations: true  # Generate supply-chain provenance
